### ISSUE TITLE
Selenium entry in requirements.txt has = but should have ==

### ISSUE THREAD

**Issue by tehryanx** [WSP-LAB/FUSE#1]
```
$ pip install -r requirements.txt 
Invalid requirement: 'selenium=3.14.1'
= is not a valid operator. Did you mean == ?
```

**Comment by leeswimming** [comment]
Yes. Thank you for reporting the typo 👍  Fixed in e6a1ef2.

**Comment by Sindadziy** [comment]
Hello!! Why does checking the file with monitorenable = true show that you can't connect to the web server, but you have logged in, which is  Problems in the  verifier_thread function. thanks!

**Comment by seongil-wi** [comment]
Thanks for the report.

I suspect that the file monitor is not properly connected to FUSE.

To solve your problem, make sure that the [file monitor](https://github.com/WSP-LAB/FUSE/blob/master/filemonitor.py) is (1) correctly configured according to `Configuration for File Monitor (Optional)` in [README.md](https://github.com/WSP-LAB/FUSE/blob/master/README.md) and (2) executed on the server where the web service is hosted.
